# Macro file for example B4

#/process/optical/cerenkov/setStackPhotons false
#/process/optical/cerenkov/setMaxPhotons 50
#/process/optical/cerenkov/setTrackSecondariesFirst true
#/process/optical/scintillation/setStackPhotons false
#/process/optical/scintillation/setTrackSecondariesFirst true

#/process/optical/processActivation absorption false
#/process/optical/processActivation wls false
#/process/optical/processActivation wls2 false
#/process/optical/processActivation boundary false
#/process/optical/processActivation rayleigh false
#/process/optical/processActivation mie false
#/process/optical/processActivation Cerenkov 0
#/process/optical/processActivation Scintillation 0
#/process/inactivate Scintillation 
#/process/inactivate Cerenkov


#/control/verbose 2
#/tracking/verbose 2
#/run/verbose 2
#/process/optical/verbose 4
#/geometry/navigator/verbose 4
#/control/cout/ignoreThreadsExcept 0
#/process/optical/... /verbose 2

/run/initialize

/analysis/setFileName data/test

/LDsensitive/gun/randomInLMO1 true
/LDsensitive/gun/randomDirection true

/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 70 40
/vis/viewer/set/hiddenEdge 1

/random/setSeeds 1 10
/run/printProgress 100000
/run/beamOn 10000
